### ISSUE TITLE
AU Linux kernel 2016 запрос на проверку linked_lists Голованов Сергей

### ISSUE THREAD

**Issue by GolovanovSrg** [GolovanovSrg/au-linux-kernel-spring-2016#1]
https://github.com/GolovanovSrg/au-linux-kernel-spring-2016/commit/65cd1b15fbdf300dd41818bf78e3912e3365f4ed

**Comment by GolovanovSrg** [comment]
Забыл удалить данные. Вот коммит с исправлением: https://github.com/GolovanovSrg/au-linux-kernel-spring-2016/commit/ff72947f9eb46e04631fbc578068033bb9298df3

**Comment by eabatalov** [comment]
Привет. Решение должно состоять из одного коммита. (на будущее)

**Comment by eabatalov** [comment]
Хорошо сделано. 4 балла из 5. Смотри комментарии в коммите.
