### ISSUE TITLE
AU Linux kernel 2016 запрос на проверку КР Голованов Сергей

### ISSUE THREAD

**Issue by GolovanovSrg** [GolovanovSrg/au-linux-kernel-spring-2016#3]
https://github.com/GolovanovSrg/au-linux-kernel-spring-2016/commit/b4130eed14736dca1358536f9d099ae6d6bafeed

**Comment by eabatalov** [comment]
In your program you find maximal available continuous virtual address range and allocated it and ranges less then this maximal range.
But you goal is to allocate all the memory including the fragmented one. Thus your solution is partial.

50 points out of 100.
